# Generated by Django 5.0.1 on 2024-01-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_code', models.AutoField(primary_key=True, serialize=False)),
                ('ad_title', models.CharField(max_length=255)),
                ('mortgage', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('buy', models.IntegerField()),
                ('main_image', models.TextField()),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('image_4', models.TextField(blank=True, null=True)),
                ('image_5', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=511, null=True)),
                ('exchange', models.IntegerField()),
                ('collaborative', models.IntegerField()),
                ('convertable', models.IntegerField()),
                ('presell', models.IntegerField()),
                ('administrative_position', models.IntegerField()),
                ('borrower', models.IntegerField()),
                ('newly_built', models.IntegerField()),
                ('in_proportionate_share', models.IntegerField()),
                ('estate_agency_aid', models.IntegerField(unique=True)),
                ('estate_agency_region_region_id', models.IntegerField(unique=True)),
                ('estate_agency_region_city_city_id', models.IntegerField(unique=True)),
                ('estate_agency_region_estate_agency_aid', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgencyManager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'agency_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstateAgency',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('aphone', models.IntegerField()),
                ('no_of_employees', models.IntegerField()),
                ('alogo', models.TextField()),
            ],
            options={
                'db_table': 'estate_agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('address', models.CharField(max_length=255)),
                ('area', models.IntegerField()),
                ('year', models.IntegerField()),
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('rooms', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('elevator', models.IntegerField()),
                ('balcony', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('storage_area', models.IntegerField()),
                ('security_guard', models.IntegerField()),
                ('loby_area', models.IntegerField()),
                ('pool', models.IntegerField()),
                ('sauna', models.IntegerField()),
                ('jacuzzi', models.IntegerField()),
                ('sports_hall_area', models.IntegerField()),
                ('air_conditioning', models.IntegerField()),
                ('conference_hall', models.IntegerField()),
                ('central_antenna', models.IntegerField()),
                ('remote_door', models.IntegerField()),
                ('roof_garden', models.IntegerField()),
                ('type', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
                ('estate_agency_aid', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=32)),
                ('creation_time', models.DateTimeField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseHasEstateAgency',
            fields=[
                ('house_house', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='kilid_app.house')),
            ],
            options={
                'db_table': 'house_has_estate_agency',
                'managed': False,
            },
        ),
    ]
